Updated 2021 Colors for Java
jiyuan0125/Github3 pull request #31
Opened 2021-10-01 20:48 UTC by napsterv

# Description
Updated text, method parameter, generic type parameter, Class/Interface color for Java

⚠️ Remember to update changelog!

## Type of change

- 🐛 bug fix

## Mentions

- [@mention](https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#mentioning-people-and-teams)

2021-10-02 13:20 UTC, bhushan commented
@napsterv asking few more people to review

2021-10-02 13:21 UTC, napsterv commented
> @napsterv asking few more people to review

Alrighty @bhushan

2021-10-02 13:23 UTC, bhushan requested changes

2021-10-02 13:23 UTC, bhushan commented on src/main/resources/GitHub_Light.xml
> -    <metaInfo>
@napsterv update exact changes which you want to be changed.. don't include formatting changes.

2021-10-02 13:23 UTC, bhushan commented on CHANGELOG.md
> +Fix Java colors for 2021
also update https://github.com/jiyuan0125/github-theme-for-jetbrains/blob/16bf1de6b2c5806a953516ce83121f5116132d14/gradle.properties#L6 this to 1.1.4

2021-10-02 13:25 UTC, bhushan commented on CHANGELOG.md
> +Fix Java colors for 2021
also please update exact changes under unreleased section as fix should not be for 2021 only

2021-10-02 13:26 UTC, bhushan requested changes

2021-10-02 13:26 UTC, bhushan commented on src/main/resources/GitHub_Light.xml
> +</scheme>
should be new line at the end of file

2021-10-02 15:43 UTC, napsterv commented
Will send a separate PR!

2021-10-02 15:43 UTC, closed without merging

2022-06-25 13:02 UTC, bhushan commented
@napsterv

2022-07-21 17:32 UTC, napsterv commented
> @napsterv 

Thanks bro!